services:
  crud_users_db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crud_users_api:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: rails server -b 0.0.0.0 -p 80
    volumes:
      - ./back:/rails
    ports:
      - "3000:80"
    depends_on:
      - crud_users_db
    environment:
      RAILS_ENV: development
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}

      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      PRIMARY_DATABASE_NAME: ${PRIMARY_DATABASE_NAME}
      QUEUE_DATABASE_NAME: ${QUEUE_DATABASE_NAME}