services:
  crud_users_db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crud_users_api:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: rails server -b 0.0.0.0
    volumes:
      - ./back:/rails
    ports:
      - "${BACK_PORT:-3000}:3000"
    depends_on:
      - crud_users_db
    env_file:
      - .env
    environment:
      RAILS_ENV: development

  solid_queue_worker:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bash -c "bin/jobs start"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    volumes:
      - ./back:/rails
    depends_on:
      - crud_users_db
  crud_users_front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "${FRONT_PORT:-5173}:5173"
    depends_on:
      - crud_users_api
    environment:
      NODE_ENV: development
      VITE_FRONT_API_BASE_URL: "http://localhost:${BACK_PORT:-3000}"
